# Generated by Django 4.2.3 on 2023-07-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_product_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='preview/', verbose_name='изображение '),
        ),
    ]
